# Generated by Django 5.2.17 on 2026-10-02 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def proteger_relatorios_postgres(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            ALTER TABLE django_classificacoes_dre ENABLE ROW LEVEL SECURITY;
            ALTER TABLE django_geracoes_relatorios ENABLE ROW LEVEL SECURITY;
            ALTER TABLE django_perfis_exportacao ENABLE ROW LEVEL SECURITY;
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                    EXECUTE 'REVOKE ALL ON TABLE django_classificacoes_dre, django_geracoes_relatorios, django_perfis_exportacao FROM anon';
                    EXECUTE 'REVOKE ALL ON SEQUENCE django_classificacoes_dre_id_seq, django_geracoes_relatorios_id_seq, django_perfis_exportacao_id_seq FROM anon';
                END IF;
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                    EXECUTE 'REVOKE ALL ON TABLE django_classificacoes_dre, django_geracoes_relatorios, django_perfis_exportacao FROM authenticated';
                    EXECUTE 'REVOKE ALL ON SEQUENCE django_classificacoes_dre_id_seq, django_geracoes_relatorios_id_seq, django_perfis_exportacao_id_seq FROM authenticated';
                END IF;
            END $$;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_auditoria_operacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoDre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.PositiveIntegerField()),
                ('prefixo_conta', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('receita', 'Receita'), ('custo', 'Custo'), ('despesa', 'Despesa'), ('outro', 'Outro')], max_length=20)),
                ('ordem', models.PositiveSmallIntegerField(default=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'classificação de DRE',
                'verbose_name_plural': 'classificações de DRE',
                'db_table': 'django_classificacoes_dre',
                'indexes': [models.Index(fields=['empresa_id', 'ordem'], name='idx_dre_empresa_ordem')],
                'constraints': [models.UniqueConstraint(fields=('empresa_id', 'prefixo_conta'), name='uq_dre_empresa_prefixo'), models.CheckConstraint(condition=models.Q(('empresa_id__gt', 0)), name='ck_dre_empresa_pos')],
            },
        ),
        migrations.CreateModel(
            name='GeracaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.PositiveIntegerField()),
                ('competencia', models.CharField(max_length=7)),
                ('tipo_relatorio', models.CharField(max_length=20)),
                ('formato', models.CharField(max_length=10)),
                ('parametros', models.JSONField(default=dict)),
                ('versao_calculo', models.CharField(max_length=20)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_gerados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'geração de relatório',
                'verbose_name_plural': 'gerações de relatórios',
                'db_table': 'django_geracoes_relatorios',
                'indexes': [models.Index(fields=['empresa_id', 'competencia', 'gerado_em'], name='idx_ger_rel_contexto')],
                'constraints': [models.CheckConstraint(condition=models.Q(('empresa_id__gt', 0)), name='ck_ger_rel_empresa_pos'), models.CheckConstraint(condition=models.Q(('competencia__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$')), name='ck_ger_rel_periodo')],
            },
        ),
        migrations.CreateModel(
            name='PerfilExportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.PositiveIntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=80)),
                ('campos', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_exportacao_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de exportação',
                'verbose_name_plural': 'perfis de exportação',
                'db_table': 'django_perfis_exportacao',
                'indexes': [models.Index(fields=['empresa_id', 'nome'], name='idx_perfil_empresa_nome')],
            },
        ),
        migrations.RunPython(proteger_relatorios_postgres, reverse_code=migrations.RunPython.noop),
    ]
