# Generated by Django 5.2.17 on 2026-10-02 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def proteger_automacoes_postgres(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            ALTER TABLE django_modelos_documentos_esperados ENABLE ROW LEVEL SECURITY;
            ALTER TABLE django_perfis_origem_entrada ENABLE ROW LEVEL SECURITY;
            ALTER TABLE django_tarefas_automacao ENABLE ROW LEVEL SECURITY;
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                    EXECUTE 'REVOKE ALL ON TABLE django_modelos_documentos_esperados, django_perfis_origem_entrada, django_tarefas_automacao FROM anon';
                    EXECUTE 'REVOKE ALL ON SEQUENCE django_modelos_documentos_esperados_id_seq, django_perfis_origem_entrada_id_seq, django_tarefas_automacao_id_seq FROM anon';
                END IF;
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                    EXECUTE 'REVOKE ALL ON TABLE django_modelos_documentos_esperados, django_perfis_origem_entrada, django_tarefas_automacao FROM authenticated';
                    EXECUTE 'REVOKE ALL ON SEQUENCE django_modelos_documentos_esperados_id_seq, django_perfis_origem_entrada_id_seq, django_tarefas_automacao_id_seq FROM authenticated';
                END IF;
            END $$;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_entregas_relatorios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDocumentoEsperado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=160)),
                ('tipo_documento', models.CharField(default='outro', max_length=20)),
                ('dia_limite', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'modelo de documento esperado',
                'verbose_name_plural': 'modelos de documentos esperados',
                'db_table': 'django_modelos_documentos_esperados',
                'indexes': [models.Index(fields=['empresa_id', 'ativo'], name='idx_doc_esperado_empresa')],
                'constraints': [models.UniqueConstraint(fields=('empresa_id', 'nome'), name='uq_doc_esperado_empresa_nome'), models.CheckConstraint(condition=models.Q(('empresa_id__gt', 0)), name='ck_doc_esperado_empresa_pos'), models.CheckConstraint(condition=models.Q(('dia_limite__isnull', True), models.Q(('dia_limite__gte', 1), ('dia_limite__lte', 31)), _connector='OR'), name='ck_doc_esperado_dia_limite')],
            },
        ),
        migrations.CreateModel(
            name='PerfilOrigemEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=80)),
                ('prefixo_nome', models.CharField(max_length=80)),
                ('pasta_referencia', models.CharField(blank=True, max_length=255)),
                ('tipo_documento', models.CharField(default='outro', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'perfil de origem de entrada',
                'verbose_name_plural': 'perfis de origem de entrada',
                'db_table': 'django_perfis_origem_entrada',
                'indexes': [models.Index(fields=['empresa_id', 'ativo', 'prefixo_nome'], name='idx_perfil_origem_empresa')],
                'constraints': [models.UniqueConstraint(fields=('empresa_id', 'nome'), name='uq_perfil_origem_empresa_nome'), models.CheckConstraint(condition=models.Q(('empresa_id__gt', 0)), name='ck_perfil_origem_empresa_pos')],
            },
        ),
        migrations.AddField(
            model_name='arquivoentradatemporario',
            name='perfil_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_identificados', to='nucleo.perfilorigementrada'),
        ),
        migrations.CreateModel(
            name='TarefaAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.PositiveIntegerField()),
                ('competencia', models.CharField(max_length=7)),
                ('tipo', models.CharField(choices=[('processar_arquivo', 'Processar arquivo'), ('verificar_pendencias', 'Verificar pendências')], max_length=30)),
                ('estado', models.CharField(choices=[('aguardando', 'Aguardando'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('falha', 'Falha')], default='aguardando', max_length=20)),
                ('detalhes', models.JSONField(default=dict)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('mensagem_erro', models.CharField(blank=True, max_length=500)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('arquivo_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_automacao', to='nucleo.arquivoentradatemporario')),
                ('solicitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_automacao_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarefa de automação',
                'verbose_name_plural': 'tarefas de automação',
                'db_table': 'django_tarefas_automacao',
                'indexes': [models.Index(fields=['empresa_id', 'competencia', 'estado'], name='idx_tarefa_auto_contexto')],
                'constraints': [models.CheckConstraint(condition=models.Q(('empresa_id__gt', 0)), name='ck_tarefa_auto_empresa_pos'), models.CheckConstraint(condition=models.Q(('competencia__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$')), name='ck_tarefa_auto_periodo'), models.CheckConstraint(condition=models.Q(('tipo__in', ['processar_arquivo', 'verificar_pendencias'])), name='ck_tarefa_auto_tipo'), models.CheckConstraint(condition=models.Q(('estado__in', ['aguardando', 'processando', 'concluida', 'falha'])), name='ck_tarefa_auto_estado')],
            },
        ),
        migrations.RunPython(proteger_automacoes_postgres, reverse_code=migrations.RunPython.noop),
    ]
