# Generated by Django 5.2.17 on 2026-10-02 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def proteger_consultas_assistente_postgres(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            ALTER TABLE django_registros_consultas_assistente ENABLE ROW LEVEL SECURITY;
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                    EXECUTE 'REVOKE ALL ON TABLE django_registros_consultas_assistente FROM anon';
                    EXECUTE 'REVOKE ALL ON SEQUENCE django_registros_consultas_assistente_id_seq FROM anon';
                END IF;
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                    EXECUTE 'REVOKE ALL ON TABLE django_registros_consultas_assistente FROM authenticated';
                    EXECUTE 'REVOKE ALL ON SEQUENCE django_registros_consultas_assistente_id_seq FROM authenticated';
                END IF;
            END $$;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_automacoes_recorrentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConsultaAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversa_id', models.PositiveIntegerField()),
                ('empresa_id', models.PositiveIntegerField()),
                ('competencia', models.CharField(max_length=7)),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('filtros', models.JSONField(default=dict)),
                ('fontes', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_assistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de consulta do assistente',
                'verbose_name_plural': 'registros de consultas do assistente',
                'db_table': 'django_registros_consultas_assistente',
                'indexes': [models.Index(fields=['empresa_id', 'competencia', 'conversa_id', 'criado_em'], name='idx_consulta_assist_contexto')],
                'constraints': [models.CheckConstraint(condition=models.Q(('conversa_id__gt', 0)), name='ck_consulta_assist_conversa_pos'), models.CheckConstraint(condition=models.Q(('empresa_id__gt', 0)), name='ck_consulta_assist_empresa_pos'), models.CheckConstraint(condition=models.Q(('competencia__regex', '^[0-9]{4}-(0[1-9]|1[0-2])$')), name='ck_consulta_assist_periodo')],
            },
        ),
        migrations.RunPython(
            proteger_consultas_assistente_postgres,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
