# Generated by Django 5.2.17 on 2026-10-07 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_registros_consultas_assistente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='arquivoentradatemporario',
            name='ck_arq_ent_extensao',
        ),
        migrations.RemoveConstraint(
            model_name='modelomapeamentoentrada',
            name='uq_mod_map_empresa_estrutura_tipo',
        ),
        migrations.AddField(
            model_name='modelomapeamentoentrada',
            name='perfil_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_mapeamento', to='nucleo.perfilorigementrada'),
        ),
        migrations.AddField(
            model_name='perfilorigementrada',
            name='modo',
            field=models.CharField(choices=[('transacional', 'Transacional'), ('contabil_estruturado', 'Contábil estruturado')], default='transacional', max_length=25),
        ),
        migrations.AddField(
            model_name='perfilorigementrada',
            name='regra_competencia',
            field=models.CharField(choices=[('restrita', 'Restrita à competência'), ('ampliada', 'Competência ampliada'), ('livre', 'Sem bloqueio de competência')], default='restrita', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='arquivoentradatemporario',
            constraint=models.CheckConstraint(condition=models.Q(('extensao__in', ('xlsx', 'xls', 'csv', 'ofx'))), name='ck_arq_ent_extensao'),
        ),
        migrations.AddConstraint(
            model_name='modelomapeamentoentrada',
            constraint=models.UniqueConstraint(condition=models.Q(('perfil_origem__isnull', True)), fields=('empresa_id', 'assinatura_estrutura', 'tipo_documento'), name='uq_mod_map_empresa_estrutura_tipo_generico'),
        ),
        migrations.AddConstraint(
            model_name='modelomapeamentoentrada',
            constraint=models.UniqueConstraint(condition=models.Q(('perfil_origem__isnull', False)), fields=('empresa_id', 'perfil_origem', 'assinatura_estrutura', 'tipo_documento'), name='uq_mod_map_empresa_perfil_estrutura_tipo'),
        ),
    ]
